theme: jekyll-theme-cayman
markdown: kramdown

navigation:
- title: Home
  url: /
- title: About
  url: /about
- title: Services
  url: /services
- title: Cases
  url: /cases
- title: Contact
  url: /contact
